apiVersion: 1

datasources:
  - name: SisPro Postgres
    uid: sispro-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: sispro
    secureJsonData:
      password: sispro_piloto
    jsonData:
      database: sispro
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
